version: "3.7"
services:
  innsecure:
    build: .
    ports:
        - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - JWT_SIGNING_STRING=SigningString
  db:
    image: postgres
    restart: always
    ports:
        - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=innsecure
    volumes:
      - ./local-init:/docker-entrypoint-initdb.d

